AWSTemplateFormatVersion: "2010-09-09"
Metadata:
    Generator: "former2"
Description: "Neptune DB Cluster with ARM64 instances"

Parameters:
  DBClusterIdentifier:
    Type: String
    Default: "db-neptune-1"
    Description: "The identifier for the Neptune DB cluster"

  DBInstanceClass:
    Type: String
    Description: "The compute and memory capacity of the DB instance"
    Default: "db.r6g.large"
    AllowedValues:
      - "db.r6g.large"     # 2 vCPU, 16 GiB RAM
      - "db.r6g.xlarge"    # 4 vCPU, 32 GiB RAM
      - "db.r6g.2xlarge"   # 8 vCPU, 64 GiB RAM
      - "db.r6g.4xlarge"   # 16 vCPU, 128 GiB RAM
      - "db.t4g.medium"    # 2 vCPU, 4 GiB RAM (burstable)

  Environment:
    Type: String
    Default: "dev"
    AllowedValues:
      - "dev"
      - "staging"
      - "prod"
    Description: "Environment type which helps determine instance size"

  NeptunePort:
    Type: Number
    Default: 8182
    Description: "The port number on which the Neptune DB accepts connections"

  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: "VPC where the Neptune cluster will be deployed"

  PrivateSubnet1:
    Type: AWS::EC2::Subnet::Id
    Description: "First private subnet for Neptune cluster"

  PrivateSubnet2:
    Type: AWS::EC2::Subnet::Id
    Description: "Second private subnet for Neptune cluster"

  AvailabilityZone1:
    Type: AWS::EC2::AvailabilityZone::Name
    Description: "Availability Zone for the primary DB instance"

  AvailabilityZone2:
    Type: AWS::EC2::AvailabilityZone::Name
    Description: "Availability Zone for the replica DB instance"

  KmsKeyId:
    Type: String
    Description: "The KMS key ID for encryption"
    Default: "c6fd0767-cf7f-4a3a-83a5-9856b2f0ce6d"
    AllowedValues:
      - "c6fd0767-cf7f-4a3a-83a5-9856b2f0ce6d"
      - "key-id-2"
      - "key-id-3"

Conditions:
  IsProduction: !Equals [!Ref Environment, "prod"]

Resources:
    NeptuneSecurityGroup:
        Type: AWS::EC2::SecurityGroup
        Properties:
            GroupDescription: Security group for Neptune cluster
            VpcId: !Ref VpcId
            SecurityGroupIngress:
                - IpProtocol: tcp
                  FromPort: !Ref NeptunePort
                  ToPort: !Ref NeptunePort
                  CidrIp: !GetAtt VpcId.CidrBlock
            Tags:
                - Key: Name
                  Value: !Sub "${DBClusterIdentifier}-sg"

    NeptuneSubnetGroup:
        Type: AWS::Neptune::DBSubnetGroup
        Properties:
            DBSubnetGroupDescription: Subnet group for Neptune cluster
            SubnetIds: 
                - !Ref PrivateSubnet1
                - !Ref PrivateSubnet2
            Tags:
                - Key: Name
                  Value: !Sub "${DBClusterIdentifier}-subnet-group"

    NeptuneDBCluster:
        Type: "AWS::Neptune::DBCluster"
        Properties:
            BackupRetentionPeriod: !If [IsProduction, 7, 1]
            DBClusterIdentifier: !Ref DBClusterIdentifier
            DBClusterParameterGroupName: "default.neptune1.4"
            DBSubnetGroupName: !Ref NeptuneSubnetGroup
            Port: !Ref NeptunePort
            PreferredBackupWindow: "07:54-08:24"
            PreferredMaintenanceWindow: "mon:03:53-mon:04:23"
            VpcSecurityGroupIds: 
              - !Ref NeptuneSecurityGroup
            StorageEncrypted: true
            KmsKeyId: !Sub "arn:aws:kms:${AWS::Region}:${AWS::AccountId}:key/${KmsKeyId}"
            IamAuthEnabled: true
            EngineVersion: "1.4.3.0"
            DeletionProtection: !If [IsProduction, true, false]
            EnableCloudwatchLogsExports: 
              - "audit"
              - "slowquery"
            Tags:
                - Key: Name
                  Value: !Sub "${DBClusterIdentifier}-cluster"
                - Key: Environment
                  Value: !Ref Environment

    PrimaryDBInstance:
        Type: AWS::Neptune::DBInstance
        Properties:
            DBClusterIdentifier: !Ref NeptuneDBCluster
            DBInstanceClass: !Ref DBInstanceClass
            AvailabilityZone: !Ref AvailabilityZone1
            Tags:
                - Key: Name
                  Value: !Sub "${DBClusterIdentifier}-primary"

    ReplicaDBInstance:
        Type: AWS::Neptune::DBInstance
        Condition: IsProduction
        Properties:
            DBClusterIdentifier: !Ref NeptuneDBCluster
            DBInstanceClass: !Ref DBInstanceClass
            AvailabilityZone: !Ref AvailabilityZone2
            Tags:
                - Key: Name
                  Value: !Sub "${DBClusterIdentifier}-replica"

Outputs:
    ClusterEndpoint:
        Description: "Neptune Cluster Endpoint"
        Value: !GetAtt NeptuneDBCluster.Endpoint

    ReaderEndpoint:
        Description: "Neptune Reader Endpoint"
        Value: !GetAtt NeptuneDBCluster.ReadEndpoint

    NeptuneSecurityGroupId:
        Description: "ID of the Neptune Security Group"
        Value: !Ref NeptuneSecurityGroup
